export const NAV_LINKS = [
  { label: 'Services', href: '#services' },
  { label: 'Work', href: '#portfolio' },
  { label: 'Process', href: '#process' },
  { label: 'About', href: '#about' },
  { label: 'Contact', href: '#contact' },
];

export const SERVICES = [
  {
    id: 1,
    title: 'Photography',
    description: 'Cinematic product & lifestyle photography that tells your brand story with depth, mood, and visual precision.',
    icon: '📸',
    color: '#00F5FF',
    featured: true,
    deliverables: ['Product shoots', 'Lifestyle photography', 'Brand identity visuals', 'Event coverage', 'Post-production editing'],
  },
  {
    id: 2,
    title: 'Website Development',
    description: 'High-performance, conversion-optimized websites built with cutting-edge technology and professional UX design.',
    icon: '💻',
    color: '#B026FF',
    featured: false,
    deliverables: ['Custom design', 'React / Next.js builds', 'CMS integration', 'SEO-ready architecture', 'Performance optimization'],
  },
  {
    id: 3,
    title: 'Ads & Shoots',
    description: 'Scroll-stopping ad campaigns with cinematic production quality that drives measurable ROI.',
    icon: '🎬',
    color: '#FFD700',
    featured: false,
    deliverables: ['Ad concept & scripting', 'Professional shoots', 'Motion graphics', 'A/B ready creatives', 'Platform-specific formats'],
  },
  {
    id: 4,
    title: 'Graphic Design',
    description: 'Bold, purposeful visual design that makes your brand impossible to ignore across every touchpoint.',
    icon: '🎨',
    color: '#FF6B6B',
    featured: false,
    deliverables: ['Brand collateral', 'Print & digital design', 'Packaging design', 'Infographics', 'Marketing materials'],
  },
  {
    id: 5,
    title: 'Logo Designing',
    description: 'Iconic logo marks that distill your brand\'s essence into a single, timeless visual statement.',
    icon: '✏️',
    color: '#00D4A1',
    featured: false,
    deliverables: ['Brand identity discovery', 'Logo concepts (3 directions)', 'Brand guidelines', 'All file formats', 'Future revision support'],
  },
  {
    id: 6,
    title: 'Social Media Management',
    description: 'Data-driven social strategies that grow your audience, build community, and drive real business results.',
    icon: '📱',
    color: '#FF9A3C',
    featured: false,
    deliverables: ['Content calendar', 'Daily posting & scheduling', 'Community management', 'Analytics reporting', 'Paid social strategy'],
  },
  {
    id: 7,
    title: 'Editing',
    description: 'Professional post-production that transforms raw footage into polished, engaging video content.',
    icon: '✂️',
    color: '#A78BFA',
    featured: false,
    deliverables: ['Video editing', 'Color grading', 'Sound design', 'Motion graphics', 'Reels & short-form content'],
  },
  {
    id: 8,
    title: 'Digital Marketing',
    description: 'Full-funnel digital marketing strategies that scale your business across every relevant channel.',
    icon: '📈',
    color: '#34D399',
    featured: false,
    deliverables: ['SEO strategy', 'PPC campaigns', 'Email marketing', 'Content marketing', 'Analytics & reporting'],
  },
];

export const PROJECTS = [
  {
    id: 1,
    name: 'Vybrant Enterprises',
    category: 'Video Production',
    tags: ['Video Production', 'Editing', 'Social Media'],
    result: 'Complete Video Production & Handling',
    description: 'We provided complete Video Production Services (VPS) including promotional videos, reels, and brand-focused visual content, alongside professional video editing for campaigns and comprehensive Social Media Handling (SMH).',
    image: '/projects/vybrant.png',
    metrics: [
      { label: 'Videos Produced', value: '30+' },
      { label: 'Engagement Rate', value: '8.5%' },
      { label: 'Brand Reach', value: '120%+' },
    ],
    testimonial: {
      quote: 'The quality of content LabGators produces is unmatched. They understand our brand and consistently deliver beyond expectations.',
      author: 'Vybrant Enterprises Team',
    },
    color: '#B026FF',
  },
  {
    id: 2,
    name: 'MGR Academy',
    category: 'Graphic Design & Editing',
    tags: ['Video Editing', 'Graphic Design', 'Education'],
    result: 'Creative Educational Branding',
    description: 'Collaborated on creative video editing projects for educational and promotional content, while designing eye-catching posters, banners, advertisements, and digital content to boost student engagement.',
    image: '/projects/mgr-academy.png',
    metrics: [
      { label: 'Creative Assets', value: '150+' },
      { label: 'Student Engagement', value: '+75%' },
      { label: 'Enrollment Boost', value: '40%' },
    ],
    testimonial: {
      quote: 'Their creative designs and educational videos significantly boosted student engagement and gave our academy a standout look.',
      author: 'MGR Academy Director',
    },
    color: '#FF3E6C',
  },
  {
    id: 3,
    name: 'Livias',
    category: 'E-commerce & Shopify',
    tags: ['Shopify', 'Web Dev', 'Social Media'],
    result: 'Shopify Store Launch',
    description: 'Developed and maintained responsive e-commerce websites with user-friendly design and functionality using Shopify, coupled with high-engagement social media campaigns and reels.',
    image: '/projects/livias.png',
    metrics: [
      { label: 'Conversion Rate', value: '3.4%' },
      { label: 'Sales Growth', value: '150%+' },
      { label: 'Audience Reach', value: '25k+' },
    ],
    testimonial: {
      quote: 'Our Shopify store\'s user experience is flawless. LabGators handled everything from UI design to our launch social media campaigns perfectly.',
      author: 'Livias Brand Founder',
    },
    color: '#00E5FF',
  },
  {
    id: 4,
    name: 'Stoy Kee',
    category: 'Website Development',
    tags: ['React', 'JavaScript', 'Graphic Design', 'Social Media'],
    result: 'React Platform & SMH',
    description: 'Designed and developed stunning business websites with React and JavaScript, managed social media handling (SMH) to improve online visibility, and created custom brand assets (logos, posters, banners).',
    image: '/projects/stoykee.png',
    metrics: [
      { label: 'Page Load Speed', value: '0.8s' },
      { label: 'Inquiry Volume', value: '90%+' },
      { label: 'Social Impression', value: '20k+' },
    ],
    testimonial: {
      quote: 'Our React website finally matches the quality of our work. LabGators understood our aesthetic immediately and delivered perfection.',
      author: 'Stoy Kee Studio',
    },
    color: '#00D4A1',
  },
  {
    id: 5,
    name: 'Cafe Mellow',
    category: 'Full Campaign',
    tags: ['Photography', 'Video Production', 'Social Media'],
    result: 'Food & Ambience Campaign',
    description: 'Conducted professional photography for food products and ambience. Produced engaging promotional videos and reels, edited visual content, and managed social media handling (SMH) to drive massive customer engagement.',
    image: '/projects/cafe-mellow.png',
    metrics: [
      { label: 'Instagram Growth', value: '400%' },
      { label: 'Footfall Increase', value: '65%' },
      { label: 'Reels Views', value: '100k+' },
    ],
    testimonial: {
      quote: 'The photos and content LabGators created for us perfectly capture the vibe of Cafe Mellow. Our customers recognize us from Instagram before they even walk in!',
      author: 'Cafe Mellow Owner',
    },
    color: '#FFD700',
  },
  {
    id: 6,
    name: 'SME Granites',
    category: 'Website Development',
    tags: ['Web Dev', 'Graphic Design', 'SEO'],
    result: 'Digital Presence & Collaterals',
    description: 'Developed and maintained the official company website to maximize customer accessibility, while designing creative brochures, banners, and product catalogs to elevate their brand presence.',
    image: '/projects/sme-granites.png',
    metrics: [
      { label: 'Client Satisfaction', value: '100%' },
      { label: 'Lead Increase', value: '3×' },
      { label: 'Uptime Rate', value: '99.9%' },
    ],
    testimonial: {
      quote: 'LabGators completely transformed how our business appears online. The website is stunning, and we\'re getting more inquiries than ever.',
      author: 'SME Granites Team',
    },
    color: '#00F5FF',
  },
  {
    id: 7,
    name: 'SPN',
    category: 'E-commerce QC & Photography',
    tags: ['Photography', 'Quality Check', 'Marketplaces'],
    result: 'Marketplace Optimization',
    description: 'Conducted professional product photography, managed and optimized product listings on Amazon, Meesho, and Flipkart, and executed rigorous e-commerce quality check (QC) processes for description and catalog accuracy.',
    image: '/projects/spn.webp',
    metrics: [
      { label: 'Listings Managed', value: '10k+' },
      { label: 'QC Accuracy', value: '99.8%' },
      { label: 'Return Rate', value: '-25%' },
    ],
    testimonial: {
      quote: 'Their QC process and professional product listing optimization have dramatically reduced returns and improved our conversions.',
      author: 'SPN Operations Lead',
    },
    color: '#FFA07A',
  },
];

export const TESTIMONIALS = [
  { quote: 'LabGators transformed our online presence completely. Best decision we ever made for our brand.', author: 'Sarah K.', company: 'SME Granites', result: '3× leads' },
  { quote: 'Our social media blew up after working with LabGators. The content quality is incredible.', author: 'Arjun M.', company: 'Cafe Mellow', result: '400% growth' },
  { quote: 'Professional, creative, and results-driven. LabGators gets it done every single time.', author: 'Priya V.', company: 'Vybrant Enterprises', result: 'Extended partnership' },
  { quote: 'The React website they built is stunning. Our clients are always complimenting the clean feel.', author: 'Ravi S.', company: 'Stoy Kee', result: '10k+ views' },
  { quote: 'Our Shopify store\'s user experience is flawless. Sales increased by 150% since launch.', author: 'Elena R.', company: 'Livias', result: '1.5× Sales Boost' },
  { quote: 'Their creative designs and educational videos significantly boosted student engagement.', author: 'Dr. Kumar', company: 'MGR Academy', result: '40% signup bump' },
  { quote: 'Their catalog QC and photography keep our listings accurate across major platforms.', author: 'Nitin J.', company: 'SPN', result: '-25% return rate' },
];

export const PROCESS_STEPS = [
  {
    step: '01',
    title: 'Discovery & Strategy',
    description: 'We deep-dive into your brand, audience, and goals to craft a bespoke strategy that aligns creativity with business outcomes.',
    icon: '🔍',
  },
  {
    step: '02',
    title: 'Creative Concept',
    description: 'Our team translates strategy into bold creative concepts — visual direction, messaging, and storytelling frameworks.',
    icon: '💡',
  },
  {
    step: '03',
    title: 'Production & Execution',
    description: 'With pixel-perfect attention to detail, we bring concepts to life — from shoots and design to code and campaigns.',
    icon: '⚙️',
  },
  {
    step: '04',
    title: 'Launch & Optimization',
    description: 'We deploy, monitor, and optimize — ensuring your brand makes maximum impact from day one and keeps improving.',
    icon: '🚀',
  },
  {
    step: '05',
    title: 'Growth & Scaling',
    description: 'Through data-driven refinement and ongoing support, we scale what works and push the boundaries of what\'s possible.',
    icon: '📈',
  },
];

export const STATS = [
  { value: 50, suffix: '+', label: 'Projects Completed' },
  { value: 98, suffix: '%', label: 'Client Satisfaction' },
  { value: 3, suffix: '+', label: 'Years of Excellence' },
  { value: 8, suffix: '', label: 'Core Services' },
];
